name: Release

on:
    workflow_dispatch:
    repository_dispatch:
        types: [semantic-release]
    push:
        branches:
            - main

jobs:
    release-pkg:
        name: Create release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'
                  registry-url: https://registry.npmjs.org

            - name: Install Node Dependencies
              run: npm ci
              env:
                  CI: TRUE

            - name: Build
              run: npm run build

            - name: semantic-release-prerequisites
              run: |
                  npm install --no-package-lock --no-save \
                    @semantic-release/commit-analyzer \
                    @semantic-release/release-notes-generator \
                    @semantic-release/changelog \
                    @semantic-release/github \
                    @semantic-release/git \
                    @semantic-release/npm \

            - name: semantic-release-dry-run
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release --dry-run

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release
