name: Release

on:
  push:
    branches:
      - main

jobs:
  release-pkg:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          registry-url: https://registry.npmjs.org

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Install Node Dependencies
        run: npm ci
        env:
          CI: TRUE

      - name: Build
        run: npm run build

      - name: Publish
        run: npm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
